### ISSUE TITLE
selecting json does not pull robinhood history

### ISSUE THREAD

**Issue by kfchou** [anthonyk1225/robinhood-to-xlsx#11]
Hey @anthonyk1225, got a new issue here. When I run the app by calling `app.py`, selecting `json` no longer prompt me to enter 2FA, and my history was not updated. Any ideas? Thanks!

**Comment by anthonyk1225** [comment]
Ah, yes. I changed up some stuff especially the ui for pulling your history and generating the xlsx files.

After you select either `json` or `xlsx` it will bring up a list of which ones you would like to generate. Now instead of having to pick one by one, you can press the space bar and pick all of the entities that you would like to generate! When you're done selecting your options, press enter.

As for the 2FA code, that's awesome that it's not asking you to enter it again. For ease of use, the first time you log in, we store the refresh token from robinhood locally on the user's computer in the sqlite db that they create. Every time you make a request after that, we use the refresh token to auth the request and it will in turn generate a new refresh token. The situation where you're going to need to enter a 2FA code again, is if the refresh token expires.

**Comment by kfchou** [comment]
Right on, that's a nice implementation!

I'm seeing some errors with the P/L calculation. Specifically, number of shares held are inaccurate for certain stocks. Can you double check this; let me know if there is any information I can provide to help resolve this issue.

**Comment by rajeshp2711** [comment]
Hi kfchou how did you get the P/L working. Please let me know i'm new here

**Comment by kfchou** [comment]
> Hi kfchou how did you get the P/L working. Please let me know i'm new here

P/L is on the 2nd tab in orders.xlsx

**Comment by rajeshp2711** [comment]
the Json is giving errors and the excel file gets created with nothing. Also its not erroring if I give wrong password also. So is it doing anything. Can you send me some instructions please

**Comment by rajeshp2711** [comment]
line 70, in generate_auth_tokens
    return response["access_token"], response["refresh_token"]
KeyError: 'access_token'

**Comment by anthonyk1225** [comment]
@kfchou if you don't mind can you open up a new issue with the topic of incorrect P/L? I'll start looking at that in the meantime.

Edit: Also could you let me know if it's incorrect in orders, options or both. Thank you!

**Comment by anthonyk1225** [comment]
hey, @Georgedumpers. Thanks for trying out the app so far. Quick question so I can help you out. Do you have 2 factor authentication enabled on your account?

**Comment by rajeshp2711** [comment]
Hi @anthonyk1225 no I do not have it enabled.
